-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기

SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(C.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
    JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
    ) AS SUB
ON C.CAR_ID = SUB.CAR_ID
WHERE C.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, C.CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, C.CAR_ID DESC