-- 상품 별 오프라인 매출 구하기
SELECT P.PRODUCT_CODE, SUM(PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P, OFFLINE_SALE AS O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE
